# Generated by Django 3.1.1 on 2020-09-10 09:16

import django.core.serializers.json
from django.db import migrations, models

import tulius.forum.threads.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_threads', '0001_squashed_0007_rights_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='data',
            field=models.JSONField(
                default=tulius.forum.threads.models.default_json,
                encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='thread',
            name='media',
            field=models.JSONField(
                default=tulius.forum.threads.models.default_json,
                encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
