# Generated by Django 2.2.13 on 2020-07-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_threads', '0003_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreadDeleteMark',
        ),
    ]
