# Generated by Django 3.1.1 on 2020-10-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_threads', '0004_auto_20201011_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='tmp1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='tmp2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='tmp3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
