# Generated by Django 3.1.1 on 2020-10-13 14:48

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    thread_model = apps.get_model('game_forum_threads', 'Thread')
    count = thread_model.objects.all().update(
        role_id=models.F('tmp1'), edit_role_id=models.F('tmp2'),
        variation_id=models.F('tmp3'))
    print(f'Updated {count} threads')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('game_forum_threads', '0007_auto_20201013_1747'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
