language: python
python:
  - "3.6"
install:
  - pip install tox
script:
  - tox -e py36
addons:
  ssh_known_hosts: tulius2.co-de.org:22
deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: dev
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
