version: '3.5'
services:
  uwsgi:
    build:
      context: ../../..
      dockerfile: Dockerfile
    networks:
      tuliusnet:
        ipv4_address: 10.5.0.20
    restart: unless-stopped
    environment:
      TULIUS_BRANCH: dev
    volumes:
      - ../../../data/media:/opt/tulius/data/media
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"

  websockets:
    build:
      context: ../../..
      dockerfile: Dockerfile
    networks:
      tuliusnet:
        ipv4_address: 10.5.0.21
    restart: unless-stopped
    command: ["python3", "/opt/tulius/async_app.py"]
    environment:
      TULIUS_BRANCH: dev
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"

networks:
  tuliusnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
    name: tuliusnet
