version: '2.4'
services:
  web:
    image: kozzztik/tulius:dev
    networks:
      tuliusnet:
        ipv4_address: 10.5.0.20
    restart: unless-stopped
    environment:
      TULIUS_BRANCH: dev
    ports:
      - 21000:21000
    volumes:
      - ../../../data/media:/opt/tulius/data/media
      - ../../../data/mail:/opt/tulius/data/mail
      - ../../../data/indexing:/opt/tulius/data/indexing
      - ../../../settings_production.py:/opt/tulius/settings_production.py
    mem_limit: 512M
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"

  celery:
    image: kozzztik/tulius:dev
    networks:
      tuliusnet:
        ipv4_address: 10.5.0.22
    restart: unless-stopped
    command: ["celery", "-A", "tulius", "worker", "-l", "warning"]
    environment:
      TULIUS_BRANCH: dev
    volumes:
      - ../../../data/mail:/opt/tulius/data/mail
      - ../../../settings_production.py:/opt/tulius/settings_production.py
    mem_limit: 512M
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"

networks:
  tuliusnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
    name: tuliusnet
    external: true
