# Generated by Django 2.2.13 on 2020-07-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_squashed_0002_auto_20180418_1722'),
        ('game_forum_threads', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='thread',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='variations',
                to='game_forum_threads.Thread', verbose_name='new forum'),
        ),
    ]
