# Generated by Django 3.1.1 on 2020-10-28 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('games', '0001_initial'),
        ('games', '0002_auto_20180418_1722')
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(
                    max_length=500, verbose_name='name')),
                ('description', models.TextField(
                    blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'skin',
                'verbose_name_plural': 'skins',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(
                    verbose_name='serial number')),
                ('name', models.CharField(
                    default='', max_length=200, verbose_name='name')),
                ('status', models.SmallIntegerField(
                    choices=[
                        (1, 'new'), (2, 'open for registration'),
                        (3, 'registration completed'), (4, 'in progress'),
                        (5, 'finishing'), (6, 'completed'),
                        (7, 'completed and open')
                    ], default=1, verbose_name='status')),
                ('announcement', models.TextField(
                    blank=True, default='', verbose_name='announcement')),
                ('announcement_preview', models.TextField(
                    blank=True, default='',
                    verbose_name='announcement preview')),
                ('short_comment', models.CharField(
                    blank=True, default='', max_length=500,
                    verbose_name='short comment')),
                ('introduction', models.TextField(
                    blank=True, default='', verbose_name='introduction')),
                ('requests_text', models.TextField(
                    blank=True, default='', verbose_name='requests text')),
                ('card_image', models.FileField(
                    blank=True, null=True, upload_to='games/card_image',
                    verbose_name='playing card image')),
                ('top_banner', models.FileField(
                    blank=True, null=True, upload_to='games/top_banner',
                    verbose_name='top banner')),
                ('bottom_banner', models.FileField(
                    blank=True, null=True, upload_to='games/bottom_banner',
                    verbose_name='bottom banner')),
                ('show_announcement', models.BooleanField(
                    default=True, verbose_name='show announcement')),
                ('deleted', models.BooleanField(
                    default=False, verbose_name='deleted')),
                ('skin', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='games', to='games.skin',
                    verbose_name='skin')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='RequestQuestion',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('question', models.CharField(
                    default='', max_length=500, verbose_name='question')),
                ('game', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='request_questions', to='games.game',
                    verbose_name='game')),
            ],
            options={
                'verbose_name': 'request question',
                'verbose_name_plural': 'request questions',
            },
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('body', models.TextField(default='', verbose_name='text')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='requested_games',
                    to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('game', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='role_requests', to='games.game',
                    verbose_name='game')),
            ],
            options={
                'verbose_name': 'role request',
                'verbose_name_plural': 'role requests',
            },
        ),
        migrations.CreateModel(
            name='RequestQuestionAnswer',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('answer', models.CharField(
                    max_length=500, verbose_name='answer')),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='answers', to='games.requestquestion',
                    verbose_name='answer')),
                ('role_request', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='answers', to='games.rolerequest',
                    verbose_name='role request')),
            ],
            options={
                'verbose_name': 'request question answer',
                'verbose_name_plural': 'request question answers',
            },
        ),
        migrations.CreateModel(
            name='GameWinner',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('game', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='winners', to='games.game',
                    verbose_name='game')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='winned_games', to=settings.AUTH_USER_MODEL,
                    verbose_name='user')),
            ],
            options={
                'verbose_name': 'game winner',
                'verbose_name_plural': 'game winners',
            },
        ),
        migrations.CreateModel(
            name='RoleRequestSelection',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('prefer_order', models.PositiveIntegerField(
                    verbose_name='prefer order')),
                ('role_request', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='selections', to='games.rolerequest',
                    verbose_name='role request')),
            ],
            options={
                'verbose_name': 'role request selection',
                'verbose_name_plural': 'role request selections',
            },
        ),
        migrations.CreateModel(
            name='GameInvite',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('status', models.SmallIntegerField(
                    choices=[
                        (1, 'new invite'), (2, 'accepted invite'),
                        (3, 'declined invite'), (4, 'occupied invite')
                    ], default=1, verbose_name='status')),
                ('create_time', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('sender', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='sended_invites',
                    to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='invites', to=settings.AUTH_USER_MODEL,
                    verbose_name='user')),
            ],
            options={
                'verbose_name': 'game invite',
                'verbose_name_plural': 'game invites',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GameGuest',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('game', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='guests', to='games.game',
                    verbose_name='game')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='guested_games', to=settings.AUTH_USER_MODEL,
                    verbose_name='user')),
            ],
            options={
                'verbose_name': 'game guest',
                'verbose_name_plural': 'game guests',
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GameAdmin',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('game', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='admins', to='games.game',
                    verbose_name='game')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='admined_games', to=settings.AUTH_USER_MODEL,
                    verbose_name='user')),
            ],
            options={
                'verbose_name': 'game admin',
                'verbose_name_plural': 'game admins',
                'unique_together': {('game', 'user')},
            },
        ),
    ]
