# Generated by Django 2.0.4 on 2018-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'serial_number',
                    models.PositiveIntegerField(
                        verbose_name='serial number')),
                (
                    'name',
                    models.CharField(
                        default='',
                        max_length=200,
                        verbose_name='name')),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[
                            (1, 'new'),
                            (2, 'open for registration'),
                            (3, 'registration completed'),
                            (4, 'in progress'),
                            (5, 'finishing'),
                            (6, 'completed'),
                            (7, 'completed and open')],
                        default=1,
                        verbose_name='status')),
                (
                    'announcement',
                    models.TextField(
                        blank=True, default='', verbose_name='announcement')),
                (
                    'announcement_preview',
                    models.TextField(
                        blank=True,
                        default='',
                        verbose_name='announcement preview')),
                (
                    'short_comment',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=500,
                        verbose_name='short comment')),
                (
                    'introduction',
                    models.TextField(
                        blank=True,
                        default='',
                        verbose_name='introduction')),
                (
                    'requests_text',
                    models.TextField(
                        blank=True,
                        default='',
                        verbose_name='requests text')),
                (
                    'card_image',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='games/card_image',
                        verbose_name='playing card image')),
                (
                    'top_banner',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='games/top_banner',
                        verbose_name='top banner')),
                (
                    'bottom_banner',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='games/bottom_banner',
                        verbose_name='bottom banner')),
                (
                    'show_announcement',
                    models.BooleanField(
                        default=True, verbose_name='show announcement')),
                (
                    'deleted',
                    models.BooleanField(
                        default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameAdmin',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
            ],
            options={
                'verbose_name': 'game admin',
                'verbose_name_plural': 'game admins',
            },
        ),
        migrations.CreateModel(
            name='GameGuest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
            ],
            options={
                'verbose_name': 'game guest',
                'verbose_name_plural': 'game guests',
            },
        ),
        migrations.CreateModel(
            name='GameInvite',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[
                            (1, 'new invite'),
                            (2, 'accepted invite'),
                            (3, 'declined invite'),
                            (4, 'occupied invite')],
                        default=1,
                        verbose_name='status')),
                (
                    'create_time',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='created at')),
            ],
            options={
                'verbose_name': 'game invite',
                'verbose_name_plural': 'game invites',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GameWinner',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
            ],
            options={
                'verbose_name': 'game winner',
                'verbose_name_plural': 'game winners',
            },
        ),
        migrations.CreateModel(
            name='RequestQuestion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'question',
                    models.CharField(
                        default='',
                        max_length=500,
                        verbose_name='question')),
            ],
            options={
                'verbose_name': 'request question',
                'verbose_name_plural': 'request questions',
            },
        ),
        migrations.CreateModel(
            name='RequestQuestionAnswer',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'answer',
                    models.CharField(
                        max_length=500,
                        verbose_name='answer')),
            ],
            options={
                'verbose_name': 'request question answer',
                'verbose_name_plural': 'request question answers',
            },
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('body', models.TextField(default='', verbose_name='text')),
            ],
            options={
                'verbose_name': 'role request',
                'verbose_name_plural': 'role requests',
            },
        ),
        migrations.CreateModel(
            name='RoleRequestSelection',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'prefer_order',
                    models.PositiveIntegerField(verbose_name='prefer order')),
            ],
            options={
                'verbose_name': 'role request selection',
                'verbose_name_plural': 'role request selections',
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'name',
                    models.CharField(max_length=500, verbose_name='name')),
                (
                    'description',
                    models.TextField(
                        blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'skin',
                'verbose_name_plural': 'skins',
            },
        ),
    ]
