# Generated by Django 2.0.4 on 2018-04-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_squashed_0002_auto_20180418_1722'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequestselection',
            name='role',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='requests',
                to='stories.Role',
                verbose_name='role'),
        ),
        migrations.AddField(
            model_name='rolerequestselection',
            name='role_request',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='selections',
                to='games.RoleRequest',
                verbose_name='role request'),
        ),
        migrations.AddField(
            model_name='rolerequest',
            name='game',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='role_requests',
                to='games.Game',
                verbose_name='game'),
        ),
    ]
