# Generated by Django 2.2.13 on 2020-09-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('forum_comments', '0001_initial'),
        ('forum_comments', '0002_migration'),
        ('forum_comments', '0003_auto_20200724_1122'),
        ('forum_comments', '0004_migrate_delete_marks'),
        ('forum_comments', '0005_delete_commentdeletemark'),
        ('forum_comments', '0006_deleted_comments')
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_threads', '0001_squashed_0007_rights_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('title', models.CharField(
                    max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('create_time', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('edit_time', models.DateTimeField(
                    blank=True, null=True, verbose_name='edited at')),
                ('deleted', models.BooleanField(
                    default=False, verbose_name='deleted')),
                ('order', models.IntegerField(verbose_name='order')),
                ('data', models.JSONField(default=dict)),
                ('media', models.JSONField(default=dict)),
                ('editor', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='forum_comments_edited',
                    to=settings.AUTH_USER_MODEL, verbose_name='edited by')),
                ('parent', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='comments', to='forum_threads.Thread',
                    verbose_name='thread')),
                ('reply', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='answers', to='forum_comments.Comment',
                    verbose_name='reply to')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='forum_comments',
                    to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['id'],
            },
        ),
    ]
