# Generated by Django 3.1.1 on 2020-09-10 09:15

import django.core.serializers.json
from django.db import migrations, models

import tulius.forum.comments.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comments', '0001_squashed_0006_deleted_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.JSONField(
                default=tulius.forum.comments.models.default_json,
                encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.JSONField(
                default=tulius.forum.comments.models.default_json,
                encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
