# Generated by Django 2.2.13 on 2020-07-24 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comments', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='editor',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='forum_comments_edited',
                to=settings.AUTH_USER_MODEL, verbose_name='edited by'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='comments', to='forum_threads.Thread',
                verbose_name='thread'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='answers', to='forum_comments.Comment',
                verbose_name='reply to'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='forum_comments', to=settings.AUTH_USER_MODEL,
                verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='created at'),
        ),
    ]
