# Generated by Django 3.1.1 on 2020-10-28 07:43

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('game_forum_comments', '0001_initial'),
        ('game_forum_comments', '0002_migration'),
        ('game_forum_comments', '0003_auto_20200724_1420'),
        ('game_forum_comments', '0004_migrate_delete_marks'),
        ('game_forum_comments', '0005_delete_commentdeletemark'),
        ('game_forum_comments', '0006_deleted_comments'),
        ('game_forum_comments', '0001_squashed_0006_deleted_comments'),
        ('game_forum_comments', '0002_auto_20200910_1216'),
        ('game_forum_comments', '0003_auto_20200913_1526'),
        ('game_forum_comments', '0004_auto_20201013_1302'),
        ('game_forum_comments', '0005_auto_20201013_1304'),
        ('game_forum_comments', '0006_auto_20201013_1306'),
        ('game_forum_comments', '0007_auto_20201013_1307'),
        ('game_forum_comments', '0008_auto_20201013_1308')
    ]

    initial = True

    dependencies = [
        ('stories', '0001_squashed_0002_auto_20200724_2142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_forum_threads', '0001_squashed_0006_auto_20201013_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('title', models.CharField(
                    max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('create_time', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('edit_time', models.DateTimeField(
                    blank=True, null=True, verbose_name='edited at')),
                ('deleted', models.BooleanField(
                    default=False, verbose_name='deleted')),
                ('order', models.IntegerField(verbose_name='order')),
                ('data', models.JSONField(
                    default=dict,
                    encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('media', models.JSONField(
                    default=dict,
                    encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('editor', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='game_forum_comments_edited',
                    to=settings.AUTH_USER_MODEL, verbose_name='edited by')),
                ('parent', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='comments', to='game_forum_threads.thread',
                    verbose_name='thread')),
                ('reply', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='answers', to='game_forum_comments.comment',
                    verbose_name='reply to')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='game_forum_comments',
                    to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('edit_role', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='edited_comments', to='stories.role')),
                ('role', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='comments', to='stories.role')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
