# Generated by Django 3.1.1 on 2020-09-10 09:16

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_comments', '0001_squashed_0006_deleted_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='comments', to='game_forum_threads.thread',
                verbose_name='thread'),
        ),
    ]
