# Generated by Django 3.1.1 on 2020-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_comments', '0002_auto_20200910_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='role_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
