# Generated by Django 3.1.1 on 2020-10-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_comments', '0003_auto_20200913_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tmp1',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='tmp2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
