# Generated by Django 3.1.1 on 2020-10-13 10:04

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    comment_model = apps.get_model('game_forum_comments', 'Comment')
    count = comment_model.objects.all().update(
        tmp1=models.F('role_id'), tmp2=models.F('edit_role_id'))
    print(f'Updated {count} comments')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('game_forum_comments', '0004_auto_20201013_1302'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
