# Generated by Django 2.2.13 on 2020-07-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_comments', '0004_migrate_delete_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentDeleteMark',
        ),
    ]
