# Generated by Django 3.1.1 on 2020-10-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_squashed_0002_auto_20200724_2142'),
        ('game_forum_comments', '0005_auto_20201013_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edit_role_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='role_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='edit_role',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='edited_comments', to='stories.role'),
        ),
        migrations.AddField(
            model_name='comment',
            name='role',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='comments', to='stories.role'),
        ),
    ]
