# Generated by Django 3.1.1 on 2020-10-13 10:07

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    comment_model = apps.get_model('game_forum_comments', 'Comment')
    count = comment_model.objects.all().update(
        role_id=models.F('tmp1'), edit_role_id=models.F('tmp2'))
    print(f'Updated {count} comments')


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_comments', '0006_auto_20201013_1306'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
