# Generated by Django 3.1.1 on 2020-10-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_comments', '0007_auto_20201013_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tmp1',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tmp2',
        ),
    ]
