# Generated by Django 2.0.4 on 2018-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCollapse',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='day')),
                ('oses', models.TextField(verbose_name='oses')),
                ('browsers', models.TextField(verbose_name='browsers')),
                ('devices', models.TextField(verbose_name='devices')),
                ('modules', models.TextField(verbose_name='devices')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilerMessage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'module_name',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default='',
                        max_length=255,
                        null=True,
                        verbose_name='module name')),
                (
                    'func_name',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default='',
                        max_length=255,
                        null=True,
                        verbose_name='function name')),
                (
                    'create_time',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name='create time')),
                (
                    'user_id',
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name='user')),
                (
                    'exec_time',
                    models.BigIntegerField(verbose_name='execution time')),
                (
                    'db_time',
                    models.BigIntegerField(verbose_name='db work time')),
                (
                    'db_count',
                    models.BigIntegerField(verbose_name='db requests count')),
                (
                    'template_time',
                    models.BigIntegerField(
                        verbose_name='template render time')),
                (
                    'template_db_time',
                    models.BigIntegerField(
                        verbose_name='template db work time')),
                (
                    'template_db_count',
                    models.BigIntegerField(
                        verbose_name='template db requests count')),
                (
                    'exec_param',
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name='execution parameter')),
                (
                    'ip',
                    models.GenericIPAddressField(verbose_name='IP')),
                (
                    'browser',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=30,
                        null=True,
                        verbose_name='browser')),
                (
                    'browser_version',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=10,
                        null=True,
                        verbose_name='browser version')),
                (
                    'os',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=30,
                        null=True,
                        verbose_name='OS')),
                (
                    'os_version',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=10,
                        null=True,
                        verbose_name='OS version')),
                (
                    'device',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=30,
                        null=True,
                        verbose_name='device')),
                (
                    'mobile',
                    models.BooleanField(
                        default=False,
                        verbose_name='is mobile')),
                (
                    'error',
                    models.BooleanField(
                        default=False,
                        verbose_name='error')),
                (
                    'thread_id',
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name='thread ID')),
            ],
            options={
                'verbose_name': 'profiler report',
                'verbose_name_plural': 'profiler reports',
                'ordering': ['module_name', 'func_name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TimeCollapse',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'day',
                    models.DateField(
                        db_index=True,
                        verbose_name='day')),
                (
                    'create_time',
                    models.DateTimeField(
                        db_index=True,
                        verbose_name='create time')),
                (
                    'calls_count',
                    models.BigIntegerField(verbose_name='calls count')),
                (
                    'anon_calls_count',
                    models.BigIntegerField(
                        verbose_name='Anonymous calls count')),
                (
                    'mobiles_count',
                    models.BigIntegerField(verbose_name='calls count')),
                (
                    'exceptions_count',
                    models.BigIntegerField(verbose_name='exceptions count')),
                (
                    'exec_time',
                    models.BigIntegerField(verbose_name='execution time')),
                (
                    'db_time',
                    models.BigIntegerField(verbose_name='db work time')),
                (
                    'db_count',
                    models.BigIntegerField(verbose_name='db requests count')),
                (
                    'template_time',
                    models.BigIntegerField(
                        verbose_name='template render time')),
                (
                    'template_db_time',
                    models.BigIntegerField(
                        verbose_name='template db work time')),
                (
                    'template_db_count',
                    models.BigIntegerField(
                        verbose_name='template db requests count')),
            ],
        ),
    ]
