# Generated by Django 3.1.1 on 2020-09-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientCollapse',
        ),
        migrations.DeleteModel(
            name='ProfilerMessage',
        ),
        migrations.DeleteModel(
            name='TimeCollapse',
        ),
    ]
