# Generated by Django 2.2.13 on 2020-09-04 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('forum', '0001_squashed_0008_auto_20200710_1019'),
        ('forum', '0002_auto_20200721_1305'),
        ('forum', '0003_auto_20200721_1610'),
        ('forum', '0004_auto_20200721_1825'),
        ('forum', '0005_auto_20200725_1542')
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(
                    max_length=500, verbose_name='name')),
                ('mime', models.CharField(
                    max_length=500, verbose_name='mime type')),
                ('body', models.FileField(
                    upload_to='forum_uploads', verbose_name='file')),
                ('file_length', models.IntegerField(
                    default=0, verbose_name='file length')),
                ('create_time', models.DateTimeField(
                    auto_now_add=True, verbose_name='uploaded at')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='forum_files', to=settings.AUTH_USER_MODEL,
                    verbose_name='user')),
            ],
            options={
                'verbose_name': 'uploaded file',
                'verbose_name_plural': 'uploaded files',
            },
        ),
    ]
