# Generated by Django 2.2.13 on 2020-07-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_squashed_0008_auto_20200710_1019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votingvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='votingvote',
            name='comment',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT,
                related_name='votes', to='forum.Comment',
                verbose_name='comment', blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingvote',
            name='tmp',
            field=models.IntegerField(default=0, verbose_name='choice'),
            preserve_default=False,
        ),
    ]
