# Generated by Django 2.0.12 on 2020-05-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180418_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadaccessright',
            name='access_level',
            field=models.SmallIntegerField(
                choices=[
                    (3, 'read and write rights'),
                    (1, 'read right'),
                    (7, 'read, write and moderate'),
                    (2, 'write only right'),
                    (5, 'read and moderate right(no write)')
                ], default=3, verbose_name='access rights'),
        ),
    ]
