# Generated by Django 2.2.13 on 2020-07-21 15:25

from django.db import migrations


def migrate_votes(apps, schema_editor):
    VotingVote = apps.get_model('forum', 'VotingVote')
    for vote in VotingVote.objects.all():
        vote.choice = vote.tmp
        vote.save()
    print('votes finally migrated')


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200721_1610'),
    ]

    operations = [
        migrations.RunPython(migrate_votes),
        migrations.RemoveField(
            model_name='votingvote',
            name='tmp',
        ),
        migrations.AlterUniqueTogether(
            name='votingvote',
            unique_together={('choice', 'user', 'comment')},
        ),
        migrations.DeleteModel(
            name='VotingChoice',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
