# Generated by Django 2.0.12 on 2020-05-16 07:37

from django.conf import settings
from django.db import migrations


def remove_all_online_marks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    OnlineUser = apps.get_model('forum', 'OnlineUser')
    OnlineUser.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20200503_2031'),
    ]

    operations = [
        migrations.RunPython(remove_all_online_marks),
        migrations.AlterUniqueTogether(
            name='onlineuser',
            unique_together={('user', 'thread')},
        ),
    ]
