# Generated by Django 2.2.13 on 2020-07-21 15:25

import django
from django.db import migrations, models


def migrate_votes(apps, schema_editor):
    VotingVote = apps.get_model('forum', 'VotingVote')
    count = VotingVote.objects.update(choice=models.F('tmp'))
    total = VotingVote.objects.all().count()
    print(f'votes finally migrated {count} of {total}')


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200721_1610'),
    ]

    operations = [
        migrations.RunPython(migrate_votes),
        migrations.RemoveField(
            model_name='votingvote',
            name='tmp',
        ),
        migrations.AlterUniqueTogether(
            name='votingvote',
            unique_together={('user', 'comment')},
        ),
        migrations.DeleteModel(
            name='VotingChoice',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
        migrations.AlterField(
            model_name='votingvote',
            name='comment',
            field=models.ForeignKey(
                blank=False, null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='votes', to='forum.Comment',
                verbose_name='comment'),
        ),

    ]
