# Generated by Django 2.2.13 on 2020-07-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200721_1825'),
        ('forum_threads', '0002_migration'),
        ('game_forum_threads', '0002_migration'),
        ('forum_rights', '0002_migrate'),
        ('forum_comments', '0002_migration'),
        ('game_forum_comments', '0002_migration'),
        ('forum_other', '0002_migration'),
        ('game_forum_other', '0002_migration'),
        ('stories', '0002_auto_20200724_2142'),
        ('gameforum', '0002_auto_20200725_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentdeletemark',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentdeletemark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='onlineuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='onlineuser',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='onlineuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='threadaccessright',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='threadaccessright',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='threadaccessright',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='threadcollapsestatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='threadcollapsestatus',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='threadcollapsestatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='threaddeletemark',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='threaddeletemark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='threadreadmark',
            name='not_readed_comment',
        ),
        migrations.RemoveField(
            model_name='threadreadmark',
            name='readed_comment',
        ),
        migrations.RemoveField(
            model_name='threadreadmark',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='threadreadmark',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='votingvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='votingvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='votingvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentDeleteMark',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='OnlineUser',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='ThreadAccessRight',
        ),
        migrations.DeleteModel(
            name='ThreadCollapseStatus',
        ),
        migrations.DeleteModel(
            name='ThreadDeleteMark',
        ),
        migrations.DeleteModel(
            name='ThreadReadMark',
        ),
        migrations.DeleteModel(
            name='VotingVote',
        ),
    ]
