# Generated by Django 2.2.13 on 2020-06-22 15:44

from django.db import migrations


def update_voting(apps, schema_editor):
    Comment = apps.get_model('forum', 'Comment')
    Voting = apps.get_model('forum', 'Voting')
    migrated = 0
    for comment in Comment.objects.filter(voting=True):
        try:
            obj = Voting.objects.get(comment=comment)
        except Voting.DoesNotExist:
            print('Voting is missed in comment {}'.format(comment))
            continue
        comment.media['voting'] = obj.pk
        comment.save()
        migrated += 1
    print('Migrated comments: {}'.format(migrated))
    for voting in Voting.objects.all():
        comment = voting.comment
        if 'voting' not in comment.media:
            print('forgotted voting in comment {}'.format(comment))
            comment.media['voting'] = voting.pk
            comment.save()
        elif comment.media['voting'] != voting.pk:
            print('Voting mismatch in comment {}'.format(comment))


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0005_auto_20200622_1818'),
    ]

    operations = [
        migrations.RunPython(update_voting),
    ]
