# Generated by Django 2.2.13 on 2020-06-30 07:59

from django.db import migrations, models
import jsonfield.fields
import tulius.forum.models


def update_thread_media(apps, schema_editor):
    Comment = apps.get_model('forum', 'Comment')
    Thread = apps.get_model('forum', 'Thread')
    migrated = 0
    for thread in Thread.objects.filter(room=False):
        first_comment = None
        if not thread.first_comment_id:
            first_comment = Comment.objects.filter(
                parent=thread).order_by('id').first()
            if first_comment:
                thread.first_comment_id = first_comment.id
                print('restored first comment for {}'.format(thread))
        if not thread.first_comment_id:
            print('No first comment for {}'.format(thread))
        if not first_comment:
            try:
                first_comment = Comment.objects.get(pk=thread.first_comment_id)
            except Comment.DoesNotExist:
                print('Comment is missed for {}'.format(thread))
                continue
        thread.body = first_comment.body
        thread.media = first_comment.media
        thread.save()
        migrated += 1
    print('Migrated threads: {}'.format(migrated))


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200622_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='voting',
        ),
        migrations.AddField(
            model_name='thread',
            name='media',
            field=jsonfield.fields.JSONField(
                default=tulius.forum.models.default_media),
        ),
        migrations.RunPython(update_thread_media),
    ]
