# Generated by Django 2.0.12 on 2020-05-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('removed_by_sender', models.BooleanField(default=False, verbose_name='removed by sender')),
                ('removed_by_receiver', models.BooleanField(default=False, verbose_name='removed by receiver')),
                ('body', models.TextField(default='', verbose_name='message body')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_recieved', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'private message',
                'verbose_name_plural': 'private messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateTalking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talking', to='pm.PrivateMessage', verbose_name='talking')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talkings_recieved', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talkings_sent', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'private talking',
                'verbose_name_plural': 'private talkings',
                'ordering': ['last'],
                'abstract': False,
            },
        ),
    ]
