# Generated by Django 2.0.4 on 2018-04-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionCookie',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'name',
                    models.CharField(max_length=50, verbose_name='name')),
                (
                    'value',
                    models.CharField(max_length=255, verbose_name='value')),
            ],
            options={
                'verbose_name': 'exception cookie',
                'verbose_name_plural': 'exception cookies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionMessage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'create_time',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Occur time')),
                (
                    'classname',
                    models.CharField(
                        max_length=50, verbose_name='class name')),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='title')),
                (
                    'location',
                    models.CharField(max_length=255, verbose_name='location')),
                (
                    'path',
                    models.CharField(max_length=255, verbose_name='path')),
                (
                    'get_data',
                    models.CharField(max_length=255, verbose_name='get')),
                (
                    'post_data',
                    models.CharField(max_length=255, verbose_name='post')),
            ],
            options={
                'verbose_name': 'exception',
                'verbose_name_plural': 'exceptions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionMETAValue',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'name',
                    models.CharField(max_length=50, verbose_name='name')),
                (
                    'value',
                    models.CharField(max_length=255, verbose_name='value')),
                (
                    'exception_message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='metas',
                        to='logger.ExceptionMessage',
                        verbose_name='exception')),
            ],
            options={
                'verbose_name': 'exception META value',
                'verbose_name_plural': 'exception META values',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionTraceback',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'filename',
                    models.CharField(
                        max_length=250, verbose_name='file name')),
                (
                    'line_num',
                    models.IntegerField(
                        default=0, verbose_name='Line number')),
                (
                    'function_name',
                    models.CharField(
                        max_length=100, verbose_name='function name')),
                (
                    'body',
                    models.CharField(max_length=250, verbose_name='text')),
                (
                    'exception_message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='traceback',
                        to='logger.ExceptionMessage',
                        verbose_name='exception')),
            ],
            options={
                'verbose_name': 'exception traceback record',
                'verbose_name_plural': 'exception traceback records',
            },
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'level',
                    models.SmallIntegerField(
                        choices=[
                            (0, 'NOT SET'),
                            (10, 'DEBUG'),
                            (20, 'INFO'),
                            (30, 'WARNING'),
                            (40, 'ERROR'),
                            (50, 'CRITICAL')],
                        db_index=True,
                        default=0,
                        verbose_name='level')),
                (
                    'create_time',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='create time')),
                (
                    'logger_name',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        null=True,
                        verbose_name='logger name')),
                (
                    'module_name',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        null=True,
                        verbose_name='module name')),
                (
                    'body',
                    models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name': 'log message',
                'verbose_name_plural': 'log messages',
                'ordering': ['-id', '-create_time'],
            },
        ),
    ]
