# Generated by Django 2.0.4 on 2018-04-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionmessage',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='exceptions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user'),
        ),
        migrations.AddField(
            model_name='exceptioncookie',
            name='exception_message',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='cookies',
                to='logger.ExceptionMessage',
                verbose_name='exception'),
        ),
    ]
