# Generated by Django 3.1.1 on 2020-09-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20180418_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceptioncookie',
            name='exception_message',
        ),
        migrations.RemoveField(
            model_name='exceptionmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exceptionmetavalue',
            name='exception_message',
        ),
        migrations.RemoveField(
            model_name='exceptiontraceback',
            name='exception_message',
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.DeleteModel(
            name='ExceptionCookie',
        ),
        migrations.DeleteModel(
            name='ExceptionMessage',
        ),
        migrations.DeleteModel(
            name='ExceptionMETAValue',
        ),
        migrations.DeleteModel(
            name='ExceptionTraceback',
        ),
    ]
