# Generated by Django 3.1.1 on 2020-10-28 08:20

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('game_forum_other', '0001_initial'),
        ('game_forum_other', '0002_migration'),
        ('game_forum_other', '0003_auto_20200724_1949'),
        ('game_forum_other', '0004_commentlike_data'),
        ('game_forum_other', '0005_migrate_likes'),
        ('game_forum_other', '0006_fix_like_variation_names'),
        ('game_forum_other', '0001_squashed_0006_fix_like_variation_names'),
        ('game_forum_other', '0002_auto_20200910_1230'),
        ('game_forum_other', '0003_auto_20200913_1818'),
        ('game_forum_other', '0004_auto_20200914_1009'),
        ('game_forum_other', '0005_auto_20200914_1239'),
    ]

    initial = True

    dependencies = [
        ('game_forum_threads', '0001_squashed_0007_rights_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_forum_threads', '0003_auto_20200912_1854'),
        ('game_forum_comments', '0001_squashed_0006_deleted_comments'),
        ('forum', '0004_auto_20200721_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadReadMark',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('thread', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='read_marks', to='game_forum_threads.thread',
                    verbose_name='thread')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='game_forum_other_read_marks',
                    to=settings.AUTH_USER_MODEL)),
                ('not_read_comment_id', models.IntegerField(
                    blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'thread read mark',
                'verbose_name_plural': 'thread read marks',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VotingVote',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('choice', models.IntegerField(verbose_name='choice')),
                ('comment', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='votes', to='game_forum_comments.comment',
                    verbose_name='comment')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='game_voting_votes',
                    to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'voting vote',
                'verbose_name_plural': 'voting votes',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='liked', to='game_forum_comments.comment',
                    verbose_name='comment')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='game_liked_comments',
                    to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('data', models.JSONField(
                    default=dict,
                    encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'verbose_name': 'comment like',
                'verbose_name_plural': 'comments likes',
            },
        ),
    ]
