# Generated by Django 3.1.1 on 2020-09-10 09:30

import django.core.serializers.json
from django.db import migrations, models

import tulius.forum.other.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_other', '0001_squashed_0006_fix_like_variation_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='data',
            field=models.JSONField(
                default=tulius.forum.other.models.default_json,
                encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
