# Generated by Django 2.2.13 on 2020-07-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum_other', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadreadmark',
            name='not_readed_comment_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='threadreadmark',
            name='thread',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='read_marks', to='game_forum_threads.Thread',
                verbose_name='thread'),
        ),
        migrations.AlterField(
            model_name='threadreadmark',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='game_forum_other_readed_threads',
                to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
