# Generated by Django 3.1.1 on 2020-09-14 07:09

import gc

from django.db import migrations


def migrate_data(apps, schema_editor):
    ThreadReadMark = apps.get_model('game_forum_other', 'ThreadReadMark')
    count = 0
    total_count = ThreadReadMark.objects.all().count()
    print(f'Migrate {total_count} read marks')
    for read_mark in ThreadReadMark.objects.all().iterator(chunk_size=1000):
        read_mark.not_read_comment_id = read_mark.not_readed_comment_id
        if read_mark.thread.deleted:
            read_mark.delete()
            continue
        read_mark.save()
        for parent_id in read_mark.thread.parents_ids:
            item = ThreadReadMark.objects.get_or_create(
                thread_id=parent_id, user_id=read_mark.user_id,
                defaults={
                    'not_read_comment_id': read_mark.not_read_comment_id,
                    'not_readed_comment_id': read_mark.not_read_comment_id,
                }
            )[0]
            if (not item.not_read_comment_id) or (
                    read_mark.not_read_comment_id and (
                        item.not_read_comment_id >
                        read_mark.not_read_comment_id)):
                item.not_read_comment_id = read_mark.not_read_comment_id
            item.save()
        count += 1
        if count % 1000 == 0:
            gc.collect()
            print(f'migrated {count} read marks')
    print(f'Read marks migrated {count} of {total_count}')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('game_forum_other', '0003_auto_20200913_1818'),
        ('game_forum_threads', '0003_auto_20200912_1854'),

    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
