version: '2.4'
services:
  web:
    image: kozzztik/tulius:master
    networks:
      tuliusnet:
        ipv4_address: 10.5.0.10
    restart: unless-stopped
    environment:
      TULIUS_BRANCH: master
    volumes:
      - ../../../data/media:/opt/tulius/data/media
      - ../../../settings_production.py:/opt/tulius/settings_production.py
    mem_limit: 1G
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"

  celery:
    image: kozzztik/tulius:master
    networks:
      tuliusnet:
        ipv4_address: 10.5.0.12
    restart: unless-stopped
    command: ["celery", "-A", "tulius", "worker", "-l", "warning"]
    environment:
      TULIUS_BRANCH: master
    volumes:
      - ../../../settings_production.py:/opt/tulius/settings_production.py
    mem_limit: 1G
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"

networks:
  tuliusnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
    name: tuliusnet
    external: true
