# Generated by Django 2.2.13 on 2020-07-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameforum', '0001_initial'),
        ('game_forum_threads', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamethreadright',
            name='thread',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='access_roles', to='game_forum_threads.Thread',
                verbose_name='thread'),
        ),
    ]
