# Generated by Django 3.1.1 on 2020-09-10 09:12

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_threads', '0001_squashed_0007_rights_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='data',
            field=models.JSONField(
                default=dict, editable=False,
                encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='thread',
            name='media',
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='thread',
            name='parents_ids',
            field=models.JSONField(
                blank=True, default=None, editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='thread',
            name='level',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='thread',
            name='parent',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='children',
                to='forum_threads.thread',
                verbose_name='parent thread'),
        ),

    ]
