# Generated by Django 3.1.1 on 2020-10-06 10:06

from django.db import migrations
from django.conf import settings
from django import apps as django_apps
from tulius.forum.elastic_search import models
from tulius.forum.elastic_search import mapping


class Reindex(models.ReindexQuery):
    def __init__(self, app_name, model_name):
        super().__init__()
        self.app_name = app_name
        self.model_name = model_name

    def progress(self, counter, all_count):
        print(
            f'migrated {counter} of {all_count} '
            f'{self.app_name}.{self.model_name}')


def migrate_data(apps, schema_editor):
    for app_name, model_name in settings.ELASTIC_MODELS:
        model = django_apps.apps.get_model(app_name, model_name)
        print(f'Rebuilding index of {app_name}.{model_name}')
        mapping.rebuild_index(model)
        print(f'start migrating {app_name}.{model_name}')
        Reindex(app_name, model_name)(model.objects.all())
        print(f'Migrated {app_name}.{model_name}')


class Migration(migrations.Migration):
    initial = True
    atomic = False
    dependencies = [
        ('forum_threads', '0004_auto_20201011_1318'),
        ('forum_comments', '0002_auto_20200910_1215'),
        ('game_forum_threads', '0004_auto_20201011_1323'),
        ('game_forum_comments', '0003_auto_20200913_1526'),
        ('tulius', '0001_squashed_0003_user_stories_author'),
        ('stories', '0001_squashed_0002_auto_20200724_2142'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
