# Generated by Django 2.0.4 on 2018-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='updated at')),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='created at')),
                (
                    'position',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name='Position')),
                (
                    'url',
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name='URL')),
                (
                    'title',
                    models.CharField(
                        max_length=200,
                        verbose_name='title')),
                (
                    'content',
                    models.TextField(
                        blank=True,
                        verbose_name='content')),
                (
                    'is_enabled',
                    models.BooleanField(verbose_name='is enabled')),
                (
                    'show_on_home',
                    models.BooleanField(verbose_name='show on home')),
            ],
            options={
                'verbose_name': 'flat page',
                'verbose_name_plural': 'flat pages',
                'ordering': ('position',),
                'abstract': False,
            },
        ),
    ]
