# Generated by Django 2.0.4 on 2018-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VK_Profile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('vk_id', models.IntegerField(unique=True)),
                ('photo', models.CharField(max_length=255)),
                ('sex', models.IntegerField(default=0)),
                (
                    'access_token',
                    models.CharField(blank=True, default='', max_length=255)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
