# Generated by Django 3.1.1 on 2020-10-28 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('forum_read_marks', '0001_initial'),
        ('forum_read_marks', '0002_auto_20200917_1525')
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_other', '0001_squashed_0005_migrate_likes'),
        ('forum_threads', '0003_auto_20200912_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadReadMark',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('not_read_comment_id', models.IntegerField(
                    blank=True, db_index=True, null=True)),
                ('thread', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='read_marks', to='forum_threads.thread')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='forum_read_marks_read_marks',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
