# Generated by Django 4.1.6 on 2023-08-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStar',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('games', models.SmallIntegerField(verbose_name='Games won')),
            ],
            options={
                'verbose_name': 'player star',
                'verbose_name_plural': 'player stars',
                'ordering': ['games'],
            },
        ),
    ]
