# Generated by Django 4.1.6 on 2023-08-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerStar',
        ),
    ]
