# Generated by Django 3.1.1 on 2020-09-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_other', '0002_auto_20200910_1229'),
        ('forum_read_marks', '0002_auto_20200917_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreadReadMark',
        ),
    ]
