# Generated by Django 2.2.13 on 2020-07-25 14:05

from django.db import migrations
import jsonfield.fields
import tulius.forum.other.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_other', '0003_auto_20200724_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='data',
            field=jsonfield.fields.JSONField(default=tulius.forum.other.models.default_json),
        ),
    ]
