# Generated by Django 2.0.4 on 2018-04-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'create_time',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='create time')),
                (
                    'size',
                    models.PositiveIntegerField(
                        default=0, verbose_name='size')),
            ],
            options={
                'verbose_name': 'backup',
                'verbose_name_plural': 'backups',
            },
        ),
        migrations.CreateModel(
            name='BackupCategory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='name')),
                (
                    'verbose_name',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='verbose name')),
                (
                    'saved_backups',
                    models.PositiveIntegerField(
                        default=0, verbose_name='saved backups')),
                (
                    'enabled',
                    models.BooleanField(default=True, verbose_name='enabled')),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='description')),
            ],
            options={
                'verbose_name': 'backup category',
                'verbose_name_plural': 'backup categories',
            },
        ),
        migrations.CreateModel(
            name='MaintainceChangelist',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'revision',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='revision')),
                (
                    'start_time',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='start time')),
                (
                    'end_time',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='end time')),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='status')),
                (
                    'state',
                    models.SmallIntegerField(
                        choices=[
                            (0, 'In progress'), (1, 'Success'), (2, 'Error')],
                        default=0,
                        verbose_name='state')),
                (
                    'waiting_user',
                    models.BooleanField(
                        default=False, verbose_name='waiting user')),
                (
                    'buildout_update_time',
                    models.BigIntegerField(
                        blank=True, editable=False, null=True)),
                (
                    'comment',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='comment')),
                (
                    'operations',
                    models.TextField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='operations')),
                (
                    'operation',
                    models.TextField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='operation')),
                (
                    'params',
                    models.TextField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='Parameters')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLogMessage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'start_time',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='start time')),
                (
                    'text',
                    models.TextField(default='', verbose_name='text')),
                (
                    'mainteince',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='messages',
                        to='installer.MaintenanceLog')),
            ],
            options={
                'verbose_name': 'Maintenance log message',
                'verbose_name_plural': 'Maintenance log messages',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'number',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='revision')),
                (
                    'author',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='revision')),
                (
                    'comment',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='revision')),
                ('time', models.DateTimeField(verbose_name='end time')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
            },
        ),
        migrations.AddField(
            model_name='maintaincechangelist',
            name='mainteince',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='installer.MaintenanceLog'),
        ),
        migrations.AddField(
            model_name='maintaincechangelist',
            name='revision',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='installer.Revision'),
        ),
        migrations.AddField(
            model_name='backup',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='backups',
                to='installer.BackupCategory',
                verbose_name='category'),
        ),
    ]
