# Generated by Django 2.0.4 on 2018-04-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'title',
                    models.CharField(
                        max_length=100,
                        verbose_name='title')),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='description')),
                (
                    'image',
                    models.ImageField(
                        upload_to='photos/', verbose_name='image')),
                (
                    'thumbnail',
                    models.ImageField(
                        upload_to='photos/thumb/', verbose_name='thumbnail')),
                (
                    'file_length',
                    models.IntegerField(
                        default=0, verbose_name='file length')),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'title',
                    models.CharField(
                        max_length=100,
                        verbose_name='title')),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='description')),
                (
                    'enabled',
                    models.BooleanField(
                        default=False, verbose_name='enabled')),
                (
                    'title_photo',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='photos.Photo',
                        verbose_name='title photo')),
            ],
            options={
                'verbose_name': 'photo album',
                'verbose_name_plural': 'photo albums',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='photos',
                to='photos.PhotoAlbum',
                verbose_name='album'),
        ),
    ]
